spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://db:5432/mydatabase
    username: myuser
    password: mypassword
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: main-service
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
    prometheus:
      enabled: true
    metrics:
      tags:
        application: main-service

weather:
  api:
    key: ${WEATHER_API_KEY}
    url: https://api.openweathermap.org/data/2.5/weather

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
mqtt-auth:
  bridge-login: iambridginit
  bridge-pass: Tw21#_$5g(9\