spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:myapp}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: main-service
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
    prometheus:
      enabled: true
    metrics:
      tags:
        application: main-service

weather:
  api:
    key: ${WEATHER_API_KEY}
    url: https://api.openweathermap.org/data/2.5/weather

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

mqtt-auth:
  bridge-login: ${MOSQUITTO_ADMIN_USER}
  bridge-pass: ${MOSQUITTO_ADMIN_PASSWORD}

kafka:
  topics:
    - name: hubs.command
      partitions: 1
      replicas: 1
