apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart-house.fullname" . }}-backend
  labels:
    {{- include "smart-house.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "smart-house.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
