apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart-house.fullname" . }}-kafka-ui
  labels:
    {{- include "smart-house.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-ui
spec:
  type: {{ .Values.kafkaUi.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "smart-house.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: kafka-ui
  ports:
    - name: http
      port: {{ .Values.kafkaUi.service.port }}
      targetPort: {{ .Values.kafkaUi.containerPort }}
