apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart-house.fullname" . }}-mosquitto
  labels:
    {{- include "smart-house.labels" . | nindent 4 }}
    app.kubernetes.io/component: mosquitto
spec:
  type: {{ .Values.mosquitto.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "smart-house.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mosquitto
  ports:
    - name: mqtt
      port: {{ .Values.mosquitto.service.port }}
      targetPort: {{ .Values.mosquitto.containerPort }}
