apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "smart-house.fullname" . }}-postgres
  labels:
    {{- include "smart-house.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  serviceName: {{ include "smart-house.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: { { include "smart-house.name" . } }
      app.kubernetes.io/instance: { { .Release.Name } }
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "smart-house.fullname" . }}-postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "smart-house.fullname" . }}-postgres-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "smart-house.fullname" . }}-postgres-secret
                  key: POSTGRES_DB

            - name: POSTGRES_INITDB_ARGS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "smart-house.fullname" . }}-postgres-config
                  key: POSTGRES_INITDB_ARGS

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "pg_isready -U $POSTGRES_USER"
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "pg_isready -U $POSTGRES_USER"
            initialDelaySeconds: 30
            periodSeconds: 10

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "smart-house.fullname" . }}-postgres-pvc