apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "smart-house.fullname" . }}-postgres-pvc
  labels:
    {{- include "smart-house.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi