apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart-house.fullname" . }}-postgres
  labels:
    {{- include "smart-house.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: { { include "smart-house.name" . } }
    app.kubernetes.io/instance: { { .Release.Name } }
    app.kubernetes.io/component: postgresql
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432