apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart-house.fullname" . }}-prometheus
  labels:
    {{- include "smart-house.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: {{ .Values.prometheus.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "smart-house.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: prometheus
  ports:
    - name: http
      port: {{ .Values.prometheus.service.port }}
      targetPort: {{ .Values.prometheus.containerPort }}
