apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smart-house.fullname" . }}-secret
  labels:
    {{- include "smart-house.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.postgresql.auth.username | quote }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  WEATHER_API_KEY: {{ .Values.backend.auth.weatherApiKey | quote }}
  MOSQUITTO_ADMIN_USER: {{ .Values.backend.auth.mosquittoAdminUser | quote }}
  MOSQUITTO_ADMIN_PASSWORD: {{ .Values.backend.auth.mosquittoAdminPassword | quote }}
  GRAFANA_ADMIN_USER: admin
  GRAFANA_ADMIN_PASSWORD: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smart-house.fullname" . }}-postgres-secret
  labels:
    {- include "smart-house.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: mypassword
  POSTGRES_DB: mydatabase
  POSTGRES_POSTGRES_PASSWORD: postgrespassword