services:
  db:
    image: postgres:18.3
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d mydatabase" ]
      interval: 5s
      timeout: 5s
      retries: 100
    networks:
      - db-net

  liquibase:
    image: liquibase/liquibase:4.33-alpine
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./liquibase:/liquibase/changelog
    command: --url=jdbc:postgresql://db:5432/mydatabase --username=myuser --password=mypassword --changeLogFile=changelog/db.changelog-master.yaml update
    networks:
      - db-net

  kafka:
    image: apache/kafka:3.7.2
    container_name: kafka
    volumes:
      - ./kafka/server.properties:/opt/kafka/config/kraft/server.properties
      #- kafka_data:/var/lib/kafka/data
    command: >
      bash -c "
        if [ ! -f /var/lib/kafka/data/meta.properties ]; then
          /opt/kafka/bin/kafka-storage.sh format -t kraft-cluster-1 -c /opt/kafka/config/kraft/server.properties;
        fi &&
        /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties
      "
    networks:
      - kafka-net

  mosquitto:
    image: iegomez/mosquitto-go-auth:3.0.0-mosquitto_2.0.18
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./mosquitto/config/mosquitto.conf:/etc/mosquitto/mosquitto.conf
    networks:
      - mqtt-net

  bridge:
    build: ./bridge
    restart: on-failure
    depends_on:
      kafka:
        condition: service_started
      mosquitto:
        condition: service_started
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "8081:8080"
    env_file:
      - .env
    networks:
      - mqtt-net
      - kafka-net
      - prometheus-net

  test-hub:
    build: ./test-hub
    command: uv run main.py
    depends_on:
      bridge:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - mqtt-net

  backend:
    build: ./main-service
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
      kafka:
        condition: service_started
    env_file:
      - .env
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - public-net
      - kafka-net
      - db-net
      - mqtt-net
      - prometheus-net
  
  frontend:
    build: ./frontend
    restart: on-failure
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      - public-net

  prometheus:
    image: prom/prometheus:v3.11.3-distroless
    depends_on:
      backend:
        condition: service_healthy
      bridge:
        condition: service_healthy
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prometheus-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - prometheus-net

networks:
  public-net:
    driver: bridge
  mqtt-net:
    driver: bridge
  kafka-net:
    driver: bridge
  db-net:
    driver: bridge
  prometheus-net:
    driver: bridge