services:
  db:
    image: postgres:18.3
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d mydatabase" ]
      interval: 5s
      timeout: 5s
      retries: 100

  liquibase:
    image: liquibase/liquibase:4.33-alpine
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./liquibase:/liquibase/changelog
    command: --url=jdbc:postgresql://db:5432/mydatabase --username=myuser --password=mypassword --changeLogFile=changelog/db.changelog-master.yaml update

  kafka:
    image: apache/kafka:3.7.2
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - ./kafka/server.properties:/opt/kafka/config/kraft/server.properties
      #- kafka_data:/var/lib/kafka/data
    command: >
      bash -c "
        if [ ! -f /var/lib/kafka/data/meta.properties ]; then
          /opt/kafka/bin/kafka-storage.sh format -t kraft-cluster-1 -c /opt/kafka/config/kraft/server.properties;
        fi &&
        /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties
      "

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8090:8080"
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092

  backend:
    build: ./main-service
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
      kafka:
        condition: service_started
    env_file:
      - .env
    ports:
      - "8080:8080"