spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://db:5432/mydatabase
    username: myuser
    password: mypassword
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: test-group
      auto-offset-reset: earliest
weather:
  api:
    key: ${WEATHER_API_KEY}
    url: https://api.openweathermap.org/data/2.5/weather
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000