spring:
  application:
    name: bridge
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "ru.tbank.common.dto"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
    prometheus:
      enabled: true
    metrics:
      tags:
        application: bridge

mqtt:
  broker: tcp://${MQTT_HOST}:${MQTT_PORT}
  clientId: backend-bridge
  username: ${MOSQUITTO_ADMIN_USER}
  password: ${MOSQUITTO_ADMIN_PASSWORD}
  topic:
    telemetry: hubs/data

kafka:
  topic:
    data: hubs.data
