spring:
  application:
    name: bridge
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "ru.tbank.common.dto"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
    prometheus:
      enabled: true
    metrics:
      tags:
        application: bridge

mqtt:
  broker: tcp://mosquitto:1883
  clientId: backend-bridge
  username: iambridginit
  password: Tw21#_$5g(9\
  topic:
    telemetry: hubs/data

kafka:
  topic:
    data: hubs.data
